// Generated by CoffeeScript 1.7.1
(function() {
  var argv, pretty;

  argv = require('minimist')(process.argv.slice(2));

  pretty = require('./lib/ga_pretty_tag');

  pretty(argv, function(rslt) {
    return console.log(rslt);
  });

}).call(this);
