// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(argv, cb) {
    var args, id, rslt, site, var1, var2, var3, var4, var5, var6, var7, x, y, _i, _len;
    if (argv['_'].length !== 1) {
      args = argv['_'];
    }
    if (argv['_'].length === 1) {
      args = argv['_'][0].split('');
    }
    if (!typeof args instanceof Array) {
      return "error - first argument must be an array";
    }
    for (y = _i = 0, _len = args.length; _i < _len; y = ++_i) {
      x = args[y];
      if (args[y] === '') {
        args[y] = 'var' + y;
      }
    }
    var1 = args[0];
    var2 = args[1];
    var3 = args[2];
    var4 = args[3];
    var5 = args[4];
    var6 = args[5];
    var7 = args[6];
    id = argv.id || '';
    site = argv.site || '';
    rslt = "<script>\n";
    rslt += "  (function(" + var1 + "," + var2 + "," + var3 + "," + var4 + "," + var5;
    rslt += "," + var6 + "," + var7 + "){" + var1 + "['GoogleAnalyticsObject']=";
    rslt += var5 + ";" + var1 + "[" + var5 + "]=" + var1 + "[" + var5;
    rslt += "]||function(){\n";
    rslt += "  (" + var1 + "[" + var5 + "].q=" + var1 + "[" + var5;
    rslt += "].q||[]).push(arguments)}," + var1 + "[" + var5 + "].l=1*new Date();";
    rslt += var6 + "=" + var2 + ".createElement(" + var3 + "),\n";
    rslt += "  " + var7 + "=" + var2 + ".getElementsByTagName(" + var3;
    rslt += ")[0];" + var5 + ".async=1;" + var6 + ".src=" + var4;
    rslt += ";" + var7 + ".parentNode.insertBefore(" + var6 + "," + var7 + ")\n";
    rslt += "  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n";
    rslt += "\n";
    rslt += "  ga('create', '" + id + "', '" + site + "');\n";
    rslt += "  ga('send', 'pageview');\n";
    rslt += "</script>";
    if (cb) {
      cb(rslt);
    }
    return rslt;
  };

}).call(this);
